language: python

sudo: false

env:
  - python=2.7
  - python=3.5

install:
- export CONDA_BASE=http://repo.continuum.io/miniconda/Miniconda3
- wget ${CONDA_BASE}-latest-Linux-x86_64.sh -O miniconda.sh;
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- conda config --set show_channel_urls True

- conda install --yes python=${python} --file conda-requirements.txt

- python setup.py install

script:
- nosetests conda_forge_webservices -v
